// publish.ts — Static site export for EMOVEL Page Builder.
// Renders the current page to HTML using Puck's Render component +
// renderToStaticMarkup, inlines theme-derived CSS, and bundles it
// into a downloadable .zip (jszip).
//
// Called from App.tsx's onPublish callback via the AppInner component,
// which has access to the active ThemeConfig through useTheme().

import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import { Render } from '@puckeditor/core';
import type { Data } from '@puckeditor/core';
import JSZip from 'jszip';

import { config } from './puck.config';
import type { ThemeConfig } from './themes';
import {
  COLOR_KEYS,
  colorVar,
  cssVarNames,
  radius,
  space,
  motion,
} from './tokens';

// ─── CSS generation ───────────────────────────────────────────────────────────

/** Full page CSS for the exported page: font imports + token vars + base reset. */
export function buildStyleCSS(theme: ThemeConfig): string {
  // Map all color tokens to CSS custom properties
  const colorVars = COLOR_KEYS.map(
    (key) => `  ${colorVar(key)}: ${theme.colors[key]};`,
  );

  // System tokens (radius, space, motion) — these are theme-independent but
  // must be present for the section inline styles to resolve correctly.
  const systemVars = [
    `  ${cssVarNames.radiusSm}:      ${radius.sm};`,
    `  ${cssVarNames.radiusMd}:      ${radius.md};`,
    `  ${cssVarNames.radiusLg}:      ${radius.lg};`,
    `  ${cssVarNames.radiusPill}:    ${radius.pill};`,
    `  ${cssVarNames.spaceSectionV}: ${space.sectionV};`,
    `  ${cssVarNames.spaceSectionH}: ${space.sectionH};`,
    `  ${cssVarNames.spaceHeroV}:    ${space.heroV};`,
    `  ${cssVarNames.spaceHeroH}:    ${space.heroH};`,
    `  ${cssVarNames.motionEase}:    ${motion.ease};`,
    `  ${cssVarNames.motionDuration}:${motion.duration};`,
  ];

  return [
    '/* Generated by EMOVEL Page Builder */',
    `/* Theme: ${theme.label} */`,
    '',
    '/* Fonts */',
    '@import url("https://fonts.googleapis.com/css2?family=Cinzel:wght@500;600&family=Hanken+Grotesk:wght@400;500;600;700&display=swap");',
    '',
    '/* Design tokens */',
    ':root {',
    ...colorVars,
    ...systemVars,
    '}',
    '',
    '/* Base reset */',
    '*, *::before, *::after { box-sizing: border-box; }',
    'html {',
    '  font-family: "Hanken Grotesk", Inter, ui-sans-serif, system-ui, sans-serif;',
    '  -webkit-font-smoothing: antialiased;',
    '  text-rendering: geometricPrecision;',
    '}',
    'body {',
    '  margin: 0;',
    '  background: var(--color-background);',
    '  color: var(--color-textPrimary);',
    '}',
    'img, svg, video { display: block; max-width: 100%; }',
    'a { color: inherit; }',
  ].join('\n');
}

// ─── HTML generation ──────────────────────────────────────────────────────────

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'page';
}

/** Render the page sections to an HTML string using Puck's Render component.
 *  The config's render functions handle all normalizations (benefits, footer links, etc.)
 *  just as they do in the live editor. */
function renderBody(data: Data): string {
  return renderToStaticMarkup(
    createElement(Render, { config, data }),
  );
}

/** Full index.html document. */
function buildIndexHTML(bodyHTML: string, title: string, styleCSS: string): string {
  const safeTitle = escapeHTML(title);
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${safeTitle}</title>
  <style>
${styleCSS}
  </style>
</head>
<body>
${bodyHTML}
</body>
</html>`;
}

// ─── ZIP download ─────────────────────────────────────────────────────────────

/** Render the page to a .zip containing a self-contained index.html and trigger download. */
export async function publishToZip(
  data: Data,
  theme: ThemeConfig,
): Promise<void> {
  // Extract page title from Puck root props; fall back to 'page'
  const title =
    typeof (data.root as { props?: { title?: string } })?.props?.title === 'string'
      ? ((data.root as { props: { title: string } }).props.title || 'page')
      : 'page';

  const bodyHTML  = renderBody(data);
  const styleCSS  = buildStyleCSS(theme);
  const indexHTML = buildIndexHTML(bodyHTML, title, styleCSS);

  const zip = new JSZip();
  zip.file('index.html', indexHTML);

  const blob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });

  const url = URL.createObjectURL(blob);
  const a   = document.createElement('a');
  a.href     = url;
  a.download = `${slugify(title)}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
